### ISSUE TITLE
Need a Fix to this

### ISSUE THREAD

**Issue by oVoidling** [react-native-web-community/react-native-web-linear-gradient#43]
(0 , a.requireNativeComponent) is not a function
TypeError: (0 , a.requireNativeComponent) is not a function
    at s (react-native-maps.js:3:2474)
    at e.getAirComponent (react-native-maps.js:3:2675)
    at r.value (react-native-maps.js:3:18241)
    at bs ([snack internals]
    at As ([snack internals]
    at nl ([snack internals]
    at Zl ([snack internals]
    at Xl ([snack internals]
    at Kl ([snack internals]
    at Ll (https://snack-web-player.s3.us-west-1.amazonaws.com/v2/46/static/js/2.5648d2a4.chunk.js:2091:2195838)

**Comment by retyui** [comment]
@oVoidling 

⚠️ Warning:  You don't need any third-party libraries to use linear gradients in React Native.
You can use the `experimental_backgroundImage` style property, which is available in React Native 0.76.x and later.


```tsx
import { Platform, StyleSheet, View } from "react-native";

const styles = StyleSheet.create({
  gradient: Platform.select({
    web: { backgroundImage: "linear-gradient(...)" }, // works in `react-native-web` by default
    default: { experimental_backgroundImage: "linear-gradient(...)" }, // 0.76.x +
  }),
});

function App() {
  return <View style={styles.gradient} />;
}
```
